// <auto-generated />
using System;
using MUnique.OpenMU.Persistence.EntityFramework.Progression;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MUnique.OpenMU.Persistence.EntityFramework.Migrations.Progression
{
    [DbContext(typeof(ProgressionContext))]
    partial class ProgressionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("progression")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.AchievementProgress", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RewardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerId", "AchievementId");

                    b.HasIndex("AccountId");

                    b.ToTable("AchievementProgress", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.ActiveTitle", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TitleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId");

                    b.ToTable("ActiveTitle", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.PrestigeProgress", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastPrestigeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.HasIndex("Level");

                    b.ToTable("PrestigeProgress", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.SeasonClaim", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId", "SeasonId", "Level", "IsPremium");

                    b.ToTable("SeasonClaim", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.SeasonPremium", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccountId", "SeasonId");

                    b.ToTable("SeasonPremium", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.SeasonProgress", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId", "SeasonId");

                    b.ToTable("SeasonProgress", "progression");
                });

            modelBuilder.Entity("MUnique.OpenMU.Persistence.Progression.UnlockedTitle", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OwnerId", "TitleId");

                    b.ToTable("UnlockedTitle", "progression");
                });
#pragma warning restore 612, 618
        }
    }
}
